.TH GOXA 1 "" "" "User Commands"
.SH NAME
goxa \- fast archiving tool written in Go
.SH SYNOPSIS
.B goxa
.RI "[mode] [flags]" " -arc=FILE [paths...]"
.br
.B goxa c
.RI "[flags] -arc=FILE [paths...]"
.br
.B goxa l
.RI "[flags] -arc=FILE"
.br
.B goxa j
.RI "[flags] -arc=FILE"
.br
.B goxa x
.RI "[flags] -arc=FILE [destination]"
.SH DESCRIPTION
GoXA is a lightweight archiver written in Go. It can create, list and extract \fB.goxa\fP archives or standard tar files. Compression, checksums and metadata preservation are optional.
.SH MODES
.TP
.B c
Create a new archive.
.TP
.B l
List archive contents.
.TP
.B j
JSON list of archive contents.
.TP
.B x
Extract files from an archive.
.SH FLAGS
Single letter flags may be combined after the mode character:
.TP
.B a
Store and restore absolute paths.
.TP
.B p
Include file permissions.
.TP
.B m
Include modification times.
.TP
.B s
Enable checksums.
.TP
.B b
Per-block checksums.
.TP
.B n
Disable compression.
.TP
.B i
Include hidden files.
.TP
.B o
Allow special files.
.TP
.B u
Use flags embedded in archive.
.TP
.B v
Verbose logging.
.TP
.B f
Force overwrite and ignore read errors.
.PP
Additional options:
.TP
.BI -arc= FILE
Archive file name.
.TP
.B -stdout
Write archive data to standard output.
.TP
.BI -files= LIST
Comma separated list of files/directories to extract.
.TP
.B -progress=false
Disable progress display.
.TP
.BI -comp= ALG
Compression algorithm (gzip, zstd, lz4, s2, snappy, brotli, xz, none).
.TP
.BI -speed= LEVEL
Compression speed (fastest, default, better, best).
.TP
.BI -format= TYPE
Archive format (goxa or tar).
.TP
.BI -retries= N
Retry reads when a file changes during processing (0 means unlimited).
.TP
.BI -retrydelay= N
Delay between retries in seconds.
.TP
.B -failonchange
Treat changed files as fatal errors.
.TP
.B -version
Print version and exit.
.SS BASE32/BASE64
Filenames ending with \fB.b32\fP or \fB.b64\fP are encoded using
Base32 or Base64 and automatically decoded on extract or list.
.SH EXAMPLES
.nf
goxa c -arc=backup.goxa mydir/
goxa capmsf -arc=backup.goxa ~/docs
goxa x -arc=backup.goxa
goxa c -arc=backup.goxa.b64 mydir/
goxa x -arc=backup.goxa.b64
.fi
.SH SEE ALSO
tar(1), gzip(1)
.SH AUTHOR
https://github.com/Distortions81
