name: Go Release Build

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build binary
      run: |
        mkdir dist
        GOOS=linux GOARCH=amd64 go build -ldflags="-w" -gcflags="all=-l=4" -o dist/goxa

    - name: Upload release artifact
      uses: softprops/action-gh-release@v1
      with:
        files: dist/goxa
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
